---
name: generate ical from kuehn
on: 
   push:
   schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '28 6 1 * *'

env:
   CALENDAR_NAME: blauetonne.ics

jobs:
   regenerate-calendar:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            # Version range or exact version of a Python version to use, using SemVer's version range syntax.
            python-version:  3.x # optional, default is 3.x
            # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv.
            cache: pipenv # optional
        - run: |
            python -m pip install --upgrade pipenv wheel
        - id: cache-pipenv
          uses: actions/cache@v3
          with:
             path: ~/.local/share/virtualenvs
             key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

        - name: Install dependencies
          if: steps.cache-pipenv.outputs.cache-hit != 'true'
          run: |
            pipenv install --deploy --dev   
        - run: pipenv run python appointments/calender_throughput.py > ${{ env.CALENDAR_NAME }}
        - uses: actions/upload-artifact@v3
          with:
            path: ${{ env.CALENDAR_NAME }}
            name: kuehl_calendar
         
         
   publish-new-calendar:
       needs: regenerate-calendar
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v3
            with:
              ref: gh-pages
          - uses: actions/download-artifact@v3
            with: 
               name: kuehl_calendar
               path: "input" 
          - run: |
              if ! diff --brief -N -u "input/${{ env.CALENDAR_NAME }}" "${{ env.CALENDAR_NAME }}" ; then
                  cp "input/${{ env.CALENDAR_NAME }}" "${{ env.CALENDAR_NAME }}"
                  git add "${{ env.CALENDAR_NAME }}"
                  git config --global user.email "github-actions@github.dn-kr.de"
                  git config --global user.name "Automatic ics update"
                  git commit -m 'Update calendar file'
                  git push
              fi 
          
       
        

